import type {
  AggregationMethod,
  ComponentAggregationRole,
  ConfigurationStatus,
  MeasurementType,
  StrategyReportingFrequency,
  TargetScope,
} from "@/features/strategy";

export const STRATEGIC_PLAN_SOURCE_REFERENCE =
  "Eastern State Strategic Dashboard 2025-2029 (8.1.25)";

export interface StrategicGoalDefinition {
  priority_slug: string;
  slug: string;
  name: string;
  description: string;
  sort_order: number;
  configuration_status?: ConfigurationStatus;
  unresolved_question?: string;
}

export interface StrategicTargetDefinition {
  scope: TargetScope;
  reporting_year?: number;
  target_year: number;
  target_value: number | null;
  target_description: string;
  configuration_status: ConfigurationStatus;
  structured_target?: Record<string, string | number | boolean | null>;
}

export interface StrategicComponentDefinition {
  slug: string;
  label: string;
  measurement_type: MeasurementType;
  unit: string;
  numerator_label?: string;
  denominator_label?: string;
  fixed_denominator?: number;
  aggregation_role?: ComponentAggregationRole;
  weight?: number;
  configuration_status?: ConfigurationStatus;
  unresolved_question?: string;
  targets?: StrategicTargetDefinition[];
}

export interface StrategicKpiDefinition {
  kpi_slug: string;
  goal_slug: string;
  measurement_type: MeasurementType;
  /** First-class reporting unit when it intentionally differs from the legacy KPI catalog. */
  unit?: string;
  reporting_frequency: StrategyReportingFrequency;
  aggregation_method: AggregationMethod;
  configuration_status: ConfigurationStatus;
  numerator_label?: string;
  denominator_label?: string;
  fixed_denominator?: number;
  calculation_precision?: number;
  required?: boolean;
  weight?: number;
  unresolved_question?: string;
  target_description?: string;
  targets?: StrategicTargetDefinition[];
  components?: StrategicComponentDefinition[];
}

const fullPlan = (
  targetYear: number,
  targetValue: number | null,
  targetDescription: string,
  configurationStatus: ConfigurationStatus = "active",
): StrategicTargetDefinition => ({
  scope: "full_plan",
  target_year: targetYear,
  target_value: targetValue,
  target_description: targetDescription,
  configuration_status: configurationStatus,
});

const annual = (
  reportingYear: number,
  targetValue: number | null,
  targetDescription: string,
  configurationStatus: ConfigurationStatus = "active",
): StrategicTargetDefinition => ({
  scope: "annual",
  reporting_year: reportingYear,
  target_year: reportingYear,
  target_value: targetValue,
  target_description: targetDescription,
  configuration_status: configurationStatus,
});

export const STRATEGIC_GOAL_DEFINITIONS: StrategicGoalDefinition[] = [
  {
    priority_slug: "visitor-experience",
    slug: "primary-interpretive-site-plan",
    name: "Develop a Primary Interpretive Site Plan",
    description: "Research, engage stakeholders, draft, approve, and adopt the primary interpretive site plan.",
    sort_order: 10,
  },
  {
    priority_slug: "visitor-experience",
    slug: "modernized-exhibits-programs",
    name: "Reimagine the Visitor Experience through Modernized Exhibits and Programs",
    description: "Renew exhibits and programs while measuring interaction, satisfaction, and attendance outcomes.",
    sort_order: 20,
  },
  {
    priority_slug: "visitor-experience",
    slug: "visitor-amenities-accessibility-navigation",
    name: "Enhance Visitor Amenities, Accessibility and Navigation",
    description: "Improve accessible amenities, navigation, comfort, and the onsite visitor experience.",
    sort_order: 30,
  },
  {
    priority_slug: "visitor-experience",
    slug: "diverse-audiences",
    name: "Broaden Programming to Attract Diverse Audiences",
    description: "Co-create programs with community organizations and encourage repeat attendance.",
    sort_order: 40,
  },
  {
    priority_slug: "visitor-experience",
    slug: "work-with-artists",
    name: "Reconceptualize Eastern State's Work with Artists",
    description: "Grow artist partnerships, audience response, and external recognition.",
    sort_order: 50,
  },
  {
    priority_slug: "historic-preservation",
    slug: "conservation-management-plan",
    name: "Advance the Conservation Management Plan",
    description: "Complete the plan, assess structures, and direct resources to conservation priorities.",
    sort_order: 10,
  },
  {
    priority_slug: "historic-preservation",
    slug: "preservation-awareness-engagement",
    name: "Increase Public Awareness of and Engagement with ESPHS's Preservation Efforts",
    description: "Use programs, giving, and audience research to deepen preservation engagement.",
    sort_order: 20,
  },
  {
    priority_slug: "historic-preservation",
    slug: "preservation-leadership-reputation",
    name: "Maintain and Grow ESPHS's Reputation as a Leader in Preservation",
    description: "Track recognition, field contributions, and preservation leadership.",
    sort_order: 30,
  },
  {
    priority_slug: "historic-preservation",
    slug: "archive-research-accessibility",
    name: "Expand Archive and Research Accessibility",
    description: "Digitize and make archival materials available online and through programs.",
    sort_order: 40,
  },
  {
    priority_slug: "historic-preservation",
    slug: "climate-responsive-solutions",
    name: "Implement Climate-Responsive Solutions",
    description: "Define and implement resilience measures and climate-friendly projects.",
    sort_order: 50,
  },
  {
    priority_slug: "workforce-development",
    slug: "workforce-program-offerings",
    name: "Expand Program Offerings",
    description: "Grow enrollment, completion, equitable participation, and outreach.",
    sort_order: 10,
  },
  {
    priority_slug: "workforce-development",
    slug: "workforce-community-partnerships",
    name: "Strengthen Community and Program Partnerships",
    description: "Build employer partnerships and measure participant satisfaction and skill development.",
    sort_order: 20,
  },
  {
    priority_slug: "workforce-development",
    slug: "career-pipelines-employment",
    name: "Continue to Grow Career Pipelines and Employment Opportunities",
    description: "Measure employment and career advancement after program completion and connect participants through public events and job fairs.",
    sort_order: 30,
  },
  {
    priority_slug: "workforce-development",
    slug: "workforce-awareness-recognition",
    name: "Expand Public Awareness and Recognition",
    description: "Track external recognition and awareness among people not currently engaged.",
    sort_order: 40,
  },
  {
    priority_slug: "justice-education",
    slug: "schools-educators-justice-education",
    name: "Engage Schools and Educators in Justice Education",
    description: "Track onsite, virtual, classroom, professional-development, digital, and geographic reach.",
    sort_order: 10,
  },
  {
    priority_slug: "justice-education",
    slug: "justice-education-partnerships-recognition",
    name: "Build Partnerships and Recognition",
    description: "Develop active school partnerships and sustain repeat school and educator engagement in justice education.",
    sort_order: 20,
  },
  {
    priority_slug: "justice-education",
    slug: "criminal-justice-dialogue",
    name: "Expand and Promote Dialogue around Criminal Justice",
    description: "Measure educator confidence and audience representation in criminal-justice dialogue.",
    sort_order: 30,
  },
  {
    priority_slug: "justice-education",
    slug: "architecture-contemporary-education",
    name: "Leverage Historic Architecture for Contemporary Education",
    description: "Develop architecture-focused interpretation and extend contemporary justice education through digital programs and resources.",
    sort_order: 40,
    configuration_status: "needs_definition",
    unresolved_question: "Confirm how digital justice-education reach should be attributed between architecture interpretation and the broader schools-and-educators program.",
  },
  {
    priority_slug: "organizational-capacity",
    slug: "diversify-revenue-streams",
    name: "Diversify Revenue Streams",
    description: "Track earned and contributed income, multiyear support, board giving, revenue composition, and referrals.",
    sort_order: 10,
  },
  {
    priority_slug: "organizational-capacity",
    slug: "optimize-facilities",
    name: "Optimize ESPHS Facilities",
    description: "Measure site-space use for revenue, mission programs, and accessible reduced-price, free, or pay-what-you-wish events.",
    sort_order: 20,
  },
  {
    priority_slug: "organizational-capacity",
    slug: "accountability-agility-growth",
    name: "Continue to Cultivate and Support a Culture of Accountability, Agility, and Growth",
    description: "Align departments, workflows, policies, and staff reviews with the strategic plan.",
    sort_order: 30,
  },
  {
    priority_slug: "organizational-capacity",
    slug: "community-civic-hub",
    name: "Strengthen Our Role as a Community and Civic Hub",
    description: "Grow sponsorship, grants, public support, and new donors.",
    sort_order: 40,
  },
];

export const STRATEGIC_KPI_DEFINITIONS: StrategicKpiDefinition[] = [
  // Reimagine Visitor Experience
  {
    kpi_slug: "interpretive-plan-milestones-on-schedule",
    goal_slug: "primary-interpretive-site-plan",
    measurement_type: "milestone",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    numerator_label: "Milestones completed on schedule",
    denominator_label: "Required milestones",
    targets: [fullPlan(2027, 100, "Complete all research, engagement, drafting, review, and finalization milestones by 2027.")],
  },
  {
    kpi_slug: "interpretive-plan-community-feedback",
    goal_slug: "primary-interpretive-site-plan",
    measurement_type: "multi_component",
    reporting_frequency: "cumulative",
    aggregation_method: "all_complete",
    configuration_status: "active",
    components: [
      { slug: "sessions", label: "Engagement sessions", measurement_type: "cumulative", unit: "sessions", targets: [fullPlan(2027, 3, "Hold three engagement sessions by 2027.")] },
      { slug: "participants", label: "Survey and focus-group participants", measurement_type: "cumulative", unit: "participants", targets: [fullPlan(2027, 400, "Engage 400 survey or focus-group participants by 2027.")] },
    ],
  },
  {
    kpi_slug: "interpretive-plan-adoption",
    goal_slug: "primary-interpretive-site-plan",
    measurement_type: "binary",
    reporting_frequency: "one_time",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [fullPlan(2027, 1, "Obtain formal Board adoption of the interpretive site plan by Q4 2027.")],
  },
  {
    kpi_slug: "exhibits-redesigned-or-installed",
    goal_slug: "modernized-exhibits-programs",
    measurement_type: "cumulative",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [
      annual(2027, 1, "Complete one redesigned, updated, or new exhibit in 2027."),
      annual(2028, 1, "Complete one redesigned, updated, or new exhibit in 2028."),
      annual(2029, 1, "Complete one redesigned, updated, or new exhibit in 2029."),
      fullPlan(2029, 3, "Complete three redesigned, updated, or new exhibits by 2029."),
    ],
  },
  {
    kpi_slug: "exhibits-with-interactive-digital",
    goal_slug: "modernized-exhibits-programs",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    numerator_label: "Exhibits with interactive or digital elements",
    denominator_label: "Total exhibits",
    targets: [fullPlan(2029, 50, "Incorporate interactive or digital elements in 50% of exhibits by 2029.")],
  },
  {
    kpi_slug: "exhibits-satisfaction-rating",
    goal_slug: "modernized-exhibits-programs",
    measurement_type: "average",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Confirm whether the board measure is average score or percent positive and define the survey scale.",
    targets: [fullPlan(2029, 75, "Reach a 75% positive-or-above satisfaction result by 2029.", "needs_definition")],
  },
  {
    kpi_slug: "program-attendance-vs-baseline",
    goal_slug: "modernized-exhibits-programs",
    measurement_type: "year_over_year",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [fullPlan(2029, 10, "Increase attendance for each applicable program 10% from its baseline by 2029.")],
  },
  {
    kpi_slug: "art-reach-accessibility-study",
    goal_slug: "visitor-amenities-accessibility-navigation",
    measurement_type: "binary",
    reporting_frequency: "one_time",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [fullPlan(2027, 1, "Complete the Art Reach Accessibility Study by 2027.")],
  },
  {
    kpi_slug: "visitor-amenities-upgraded",
    goal_slug: "visitor-amenities-accessibility-navigation",
    measurement_type: "cumulative",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [fullPlan(2029, 5, "Complete five visitor amenity upgrades by 2029.")],
  },
  {
    kpi_slug: "amenities-navigation-satisfaction",
    goal_slug: "visitor-amenities-accessibility-navigation",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    numerator_label: "Positive amenity and navigation responses",
    denominator_label: "Amenity and navigation responses",
    targets: [fullPlan(2029, 70, "Reach a 70% satisfaction rate for amenities and navigation by 2029.")],
  },
  {
    kpi_slug: "average-dwell-time",
    goal_slug: "visitor-amenities-accessibility-navigation",
    measurement_type: "average",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Complete the timing and tracking study, establish a baseline, and finalize the dwell-time target in minutes.",
    target_description: "Target not finalized pending a timing and tracking study.",
  },
  {
    kpi_slug: "programs-cocreated-community-orgs",
    goal_slug: "diverse-audiences",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [annual(2027, 5, "Deliver five co-created community programs per year.")],
  },
  {
    kpi_slug: "repeat-attendance-increase",
    goal_slug: "diverse-audiences",
    measurement_type: "year_over_year",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the repeat-attendance growth target and denominator definition.",
  },
  {
    kpi_slug: "artist-residencies-commissions",
    goal_slug: "work-with-artists",
    measurement_type: "cumulative",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [fullPlan(2029, 4, "Establish four new or renewed residencies, commissions, or partnerships by 2029.")],
  },
  {
    kpi_slug: "artist-installations-visitor-feedback",
    goal_slug: "work-with-artists",
    measurement_type: "average",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Define whether artist-led feedback uses NPS, average score, or percent positive and finalize its target.",
  },
  {
    kpi_slug: "art-press-features-awards",
    goal_slug: "work-with-artists",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Confirm whether the annual completion threshold is two placements, three placements, or a target range.",
    target_description: "Working target: 2-3 placements per year.",
  },

  // Advance Historic Preservation
  {
    kpi_slug: "conservation-plan-revised",
    goal_slug: "conservation-management-plan",
    measurement_type: "milestone",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [fullPlan(2029, 80, "Address 80% of identified conservation-management needs by 2029.")],
  },
  {
    kpi_slug: "historic-structures-assessed",
    goal_slug: "conservation-management-plan",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    numerator_label: "Historic structures assessed and documented",
    denominator_label: "Historic structures in scope",
    unresolved_question: "Confirm the structures in scope and whether the 2027 Master Plan update is the target or a reporting milestone.",
    target_description: "Master Plan update by 2027 with annual Board review; numeric target not finalized.",
  },
  {
    kpi_slug: "conservation-funds-utilized",
    goal_slug: "conservation-management-plan",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "sum",
    configuration_status: "needs_definition",
    unresolved_question: "Define the conservation funding streams and annual goals by funding type.",
  },
  {
    kpi_slug: "preservation-tours-talks-events",
    goal_slug: "preservation-awareness-engagement",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [annual(2027, 3, "Host three preservation-focused programs annually.")],
  },
  {
    kpi_slug: "preservation-campaign-donors",
    goal_slug: "preservation-awareness-engagement",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Choose donor count, preservation-funding growth, or both, and finalize the target.",
  },
  {
    kpi_slug: "visitors-aware-of-preservation",
    goal_slug: "preservation-awareness-engagement",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    numerator_label: "Respondents aware of preservation efforts",
    denominator_label: "Survey respondents",
    unresolved_question: "Finalize the awareness target and survey population.",
  },
  {
    kpi_slug: "preservation-awards-recognitions",
    goal_slug: "preservation-leadership-reputation",
    measurement_type: "milestone",
    reporting_frequency: "cumulative",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize a calculable recognition target while retaining the 2029 intent.",
    targets: [fullPlan(2029, null, "Receive preservation recognition by 2029.", "needs_target")],
  },
  {
    kpi_slug: "preservation-speaking-engagements",
    goal_slug: "preservation-leadership-reputation",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize an annual or full-plan target for speaking engagements, presentations, and publications.",
  },
  {
    kpi_slug: "preservation-leadership-positions",
    goal_slug: "preservation-leadership-reputation",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the target for national or regional preservation leadership positions.",
  },
  {
    kpi_slug: "archival-materials-digitized-online",
    goal_slug: "archive-research-accessibility",
    measurement_type: "multi_component",
    reporting_frequency: "cumulative",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Replace TK digitization and online-availability targets with approved values and target years.",
    target_description: "Digitize TK% by TK; target not finalized.",
    components: [
      { slug: "digitized", label: "Archival materials digitized", measurement_type: "percentage", unit: "%", numerator_label: "Materials digitized", denominator_label: "Archival materials in scope", configuration_status: "needs_target" },
      { slug: "available-online", label: "Digitized materials available online", measurement_type: "percentage", unit: "%", numerator_label: "Materials available online", denominator_label: "Archival materials in scope", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "archival-materials-available-programs",
    goal_slug: "archive-research-accessibility",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    numerator_label: "Archival materials available through programs",
    denominator_label: "Archival materials in scope",
    unresolved_question: "Finalize the program-access target and denominator.",
  },
  {
    kpi_slug: "high-risk-areas-climate-resilience",
    goal_slug: "climate-responsive-solutions",
    measurement_type: "percentage",
    reporting_frequency: "cumulative",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    numerator_label: "High-risk areas with implemented resilience measures",
    denominator_label: "High-risk areas in scope",
    unresolved_question: "Define a high-risk area, the assessed area denominator, and the approved resilience measures with Liz.",
  },
  {
    kpi_slug: "climate-friendly-projects",
    goal_slug: "climate-responsive-solutions",
    measurement_type: "cumulative",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the target for projects that increase climate-friendly spaces.",
  },

  // Expand Workforce Development
  {
    kpi_slug: "workforce-program-completion-rate",
    goal_slug: "workforce-program-offerings",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Confirm the completion target and whether the Board's 10/year and 50% placement notes apply to this measure.",
    components: [
      { slug: "enrolled", label: "Participants enrolled", measurement_type: "count", unit: "participants", configuration_status: "needs_target" },
      { slug: "graduated", label: "Participants graduating", measurement_type: "count", unit: "participants", configuration_status: "needs_target" },
      { slug: "completion-rate", label: "Program completion rate", measurement_type: "percentage", unit: "%", numerator_label: "Participants graduating", denominator_label: "Participants enrolled", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "workforce-underrepresented-participants",
    goal_slug: "workforce-program-offerings",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    numerator_label: "Underrepresented or justice-impacted participants",
    denominator_label: "Workforce participants",
    unresolved_question: "Finalize the representation target and reporting definition.",
  },
  {
    kpi_slug: "workforce-outreach-engagement",
    goal_slug: "workforce-program-offerings",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the outreach-engagement target.",
  },
  {
    kpi_slug: "workforce-employer-partnerships",
    goal_slug: "workforce-community-partnerships",
    measurement_type: "year_over_year",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    targets: [fullPlan(2027, 20, "Grow strategic employer and workforce-organization partnerships 20% from the baseline by 2027.")],
  },
  {
    kpi_slug: "workforce-satisfaction-skill-improvement",
    goal_slug: "workforce-community-partnerships",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Define the satisfaction and skill-improvement scales, raw inputs, and targets independently.",
    components: [
      { slug: "satisfaction", label: "Participant satisfaction", measurement_type: "average", unit: "% normalized", configuration_status: "needs_definition" },
      { slug: "skill-improvement", label: "Self-reported skill improvement", measurement_type: "average", unit: "% normalized", configuration_status: "needs_definition" },
    ],
  },
  {
    kpi_slug: "workforce-graduates-employment",
    goal_slug: "career-pipelines-employment",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    numerator_label: "Graduates employed or advancing careers",
    denominator_label: "Program graduates",
    unresolved_question: "Define the TK follow-up period and confirm whether the 60% full-time-role note is the intended graduate outcome target.",
  },
  {
    kpi_slug: "workforce-public-events-job-fairs",
    goal_slug: "career-pipelines-employment",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the public-event target.",
  },
  {
    kpi_slug: "workforce-external-recognitions",
    goal_slug: "workforce-awareness-recognition",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the external-recognition target.",
  },
  {
    kpi_slug: "workforce-awareness-non-engaged",
    goal_slug: "workforce-awareness-recognition",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    numerator_label: "Non-engaged respondents aware of workforce programs",
    denominator_label: "Surveyed non-engaged community members, employers, and funders",
    unresolved_question: "Define the non-engaged survey population, sampling method, Year-1 baseline, and annual X% target.",
  },

  // Support Learning through Justice Education
  {
    kpi_slug: "justice-ed-total-participants",
    goal_slug: "schools-educators-justice-education",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Replace TK visit/workshop and video-view growth targets with approved component targets.",
    components: [
      { slug: "field-trip-participants", label: "Onsite field-trip participants", measurement_type: "count", unit: "participants", configuration_status: "needs_target" },
      { slug: "virtual-participants", label: "Virtual-program participants", measurement_type: "count", unit: "participants", configuration_status: "needs_target" },
      { slug: "classroom-participants", label: "Classroom-curriculum participants", measurement_type: "count", unit: "participants", configuration_status: "needs_target" },
      { slug: "workshops", label: "Justice-education workshops", measurement_type: "count", unit: "workshops", configuration_status: "needs_target" },
      { slug: "education-video-views", label: "Education video views", measurement_type: "count", unit: "views", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "justice-ed-teachers-pd",
    goal_slug: "schools-educators-justice-education",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    components: [
      { slug: "pd-attendees", label: "Teachers attending professional development", measurement_type: "count", unit: "teachers", configuration_status: "needs_target" },
      { slug: "resource-users", label: "Teachers using ESPHS resources", measurement_type: "count", unit: "teachers", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "justice-ed-online-digital-attendance",
    goal_slug: "architecture-contemporary-education",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    components: [
      { slug: "web-page-views", label: "Justice-education web page views", measurement_type: "count", unit: "views", configuration_status: "needs_target" },
      { slug: "lesson-plan-clicks", label: "Lesson-plan downloads or clicks", measurement_type: "count", unit: "clicks", configuration_status: "needs_target" },
      { slug: "video-views", label: "Justice-education video views", measurement_type: "count", unit: "views", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "justice-ed-states-represented",
    goal_slug: "schools-educators-justice-education",
    measurement_type: "ratio",
    unit: "%",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    numerator_label: "States represented",
    denominator_label: "U.S. states",
    fixed_denominator: 50,
    unresolved_question: "Finalize the target percentage of states represented.",
  },
  {
    kpi_slug: "justice-ed-school-partnerships",
    goal_slug: "justice-education-partnerships-recognition",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Replace the source's TK organization count with an approved 2027 target.",
    target_description: "Partnerships with TK organizations by 2027; target not finalized.",
  },
  {
    kpi_slug: "justice-ed-educator-confidence",
    goal_slug: "criminal-justice-dialogue",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    numerator_label: "Educators reporting increased confidence and skills",
    denominator_label: "Educator respondents",
    unresolved_question: "Finalize the educator-confidence target and confirm how the TK dialogues/learners note relates to it.",
  },
  {
    kpi_slug: "justice-ed-returning-schools-educators",
    goal_slug: "justice-education-partnerships-recognition",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    components: [
      { slug: "returning-schools", label: "Schools returning", measurement_type: "percentage", unit: "%", numerator_label: "Returning schools", denominator_label: "Schools in the prior cohort", configuration_status: "needs_target" },
      { slug: "returning-educators", label: "Educators returning", measurement_type: "percentage", unit: "%", numerator_label: "Returning educators", denominator_label: "Educators in the prior cohort", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "justice-ed-diverse-demographics",
    goal_slug: "criminal-justice-dialogue",
    measurement_type: "distribution",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Define race/ethnicity, age, and socioeconomic bands, exclusivity rules, and the representation target without assuming respondents represent all visitors.",
  },
  {
    kpi_slug: "architecture-focused-programs",
    goal_slug: "architecture-contemporary-education",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Replace the TK program count with an approved target.",
  },

  // Enhance Organizational Capacity
  {
    kpi_slug: "earned-income-yoy-growth",
    goal_slug: "diversify-revenue-streams",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize earned-income and contributed-income share or growth targets without conflating the two measures.",
    components: [
      { slug: "earned-income-share", label: "Earned income as a portion of total revenue", measurement_type: "percentage", unit: "%", numerator_label: "Earned income", denominator_label: "Total revenue", configuration_status: "needs_target" },
      { slug: "contributed-income-share", label: "Contributed income as a portion of total revenue", measurement_type: "percentage", unit: "%", numerator_label: "Contributed income", denominator_label: "Total revenue", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "multi-year-grants-pledges-value",
    goal_slug: "diversify-revenue-streams",
    measurement_type: "currency",
    unit: "USD",
    reporting_frequency: "annual",
    aggregation_method: "none",
    calculation_precision: 2,
    configuration_status: "needs_target",
    unresolved_question: "Finalize the multiyear grant and pledge target.",
  },
  {
    kpi_slug: "board-giving-participation",
    goal_slug: "diversify-revenue-streams",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "active",
    numerator_label: "Board members giving",
    denominator_label: "Board members",
    targets: [annual(2027, 100, "Reach 100% Board participation in annual giving.")],
  },
  {
    kpi_slug: "referrals-cultivated",
    goal_slug: "diversify-revenue-streams",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Define referral, cultivation, category denominators, and the TK referral/cultivation targets.",
    components: [
      { slug: "individual-prospects", label: "Individual prospect referrals", measurement_type: "count", unit: "referrals", configuration_status: "needs_definition" },
      { slug: "foundation-prospects", label: "Foundation prospect referrals", measurement_type: "count", unit: "referrals", configuration_status: "needs_definition" },
      { slug: "corporate-prospects", label: "Corporate prospect referrals", measurement_type: "count", unit: "referrals", configuration_status: "needs_definition" },
    ],
  },
  {
    kpi_slug: "revenue-by-stream",
    goal_slug: "diversify-revenue-streams",
    measurement_type: "multi_component",
    unit: "USD",
    reporting_frequency: "annual",
    aggregation_method: "sum",
    calculation_precision: 2,
    configuration_status: "needs_target",
    unresolved_question: "Finalize targets for the revenue-stream composition while preserving each raw currency amount and total revenue denominator.",
    components: [
      "Admissions",
      "Memberships",
      "Grants",
      "Donations",
      "Endowment Income",
      "Corporate Sponsorships",
      "Retail",
      "Rentals",
    ].map((label) => ({
      slug: label.toLowerCase().replaceAll(" ", "-"),
      label: `${label} revenue`,
      measurement_type: "currency" as const,
      unit: "USD",
      configuration_status: "needs_target" as const,
    })),
  },
  {
    kpi_slug: "spaces-utilized-revenue-programs",
    goal_slug: "optimize-facilities",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    numerator_label: "Spaces utilized for revenue and programs",
    denominator_label: "Site spaces in scope",
    unresolved_question: "Define the facilities denominator and finalize the utilization target.",
  },
  {
    kpi_slug: "departments-aligned-best-practices",
    goal_slug: "accountability-agility-growth",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_definition",
    unresolved_question: "Define aligned departments, workflows, and compliant/updated policies and set targets for each.",
    components: [
      { slug: "departments", label: "Departments aligned with strategic goals", measurement_type: "percentage", unit: "%", numerator_label: "Aligned departments", denominator_label: "Departments in scope", configuration_status: "needs_definition" },
      { slug: "workflows", label: "Workflows aligned with best practices", measurement_type: "percentage", unit: "%", numerator_label: "Aligned workflows", denominator_label: "Workflows in scope", configuration_status: "needs_definition" },
      { slug: "policies", label: "Institutional policies updated", measurement_type: "percentage", unit: "%", numerator_label: "Updated policies", denominator_label: "Policies in scope", configuration_status: "needs_definition" },
    ],
  },
  {
    kpi_slug: "staff-reviews-strategic-alignment",
    goal_slug: "accountability-agility-growth",
    measurement_type: "percentage",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    numerator_label: "Staff reviews showing strategic alignment",
    denominator_label: "Completed staff reviews",
    unresolved_question: "Finalize the institution-wide alignment target.",
  },
  {
    kpi_slug: "new-corporate-sponsorships-grants",
    goal_slug: "community-civic-hub",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Replace TK sponsorship, foundation grant, and accessible-event targets with approved values.",
    components: [
      { slug: "corporate-sponsorships", label: "New corporate sponsorships", measurement_type: "count", unit: "sponsorships", configuration_status: "needs_target" },
      { slug: "foundation-grants", label: "New foundation grants", measurement_type: "count", unit: "grants", configuration_status: "needs_target" },
      { slug: "sponsorship-grant-value", label: "Value of new sponsorships and grants", measurement_type: "currency", unit: "USD", configuration_status: "needs_target" },
      { slug: "accessible-events", label: "Reduced-price, free, or PWYW events", measurement_type: "count", unit: "events", configuration_status: "needs_target" },
    ],
  },
  {
    kpi_slug: "reduced-price-free-pwyw-events",
    goal_slug: "optimize-facilities",
    measurement_type: "count",
    reporting_frequency: "annual",
    aggregation_method: "none",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the annual reduced-price, free, or PWYW event target.",
  },
  {
    kpi_slug: "government-support-percentage",
    goal_slug: "community-civic-hub",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "ratio",
    configuration_status: "needs_target",
    unresolved_question: "Finalize the government-support target as a portion of contributed revenue.",
    components: [
      {
        slug: "city-support",
        label: "City government support",
        measurement_type: "currency",
        unit: "USD",
        aggregation_role: "numerator",
        configuration_status: "needs_target",
      },
      {
        slug: "state-support",
        label: "State government support",
        measurement_type: "currency",
        unit: "USD",
        aggregation_role: "numerator",
        configuration_status: "needs_target",
      },
      {
        slug: "contributed-revenue",
        label: "Contributed revenue",
        measurement_type: "currency",
        unit: "USD",
        aggregation_role: "denominator",
        configuration_status: "needs_target",
      },
    ],
  },
  {
    kpi_slug: "new-individual-institutional-donors",
    goal_slug: "community-civic-hub",
    measurement_type: "multi_component",
    reporting_frequency: "annual",
    aggregation_method: "sum",
    configuration_status: "needs_target",
    unresolved_question: "Finalize separate targets for new individual and institutional donors.",
    components: [
      { slug: "individual-donors", label: "New individual donors", measurement_type: "count", unit: "donors", configuration_status: "needs_target" },
      { slug: "institutional-donors", label: "New institutional donors", measurement_type: "count", unit: "donors", configuration_status: "needs_target" },
    ],
  },
];
