/** Client-safe strategic-plan domain facade. */
export {
  AGGREGATION_METHODS,
  AVERAGE_INPUT_METHODS,
  BOARD_STATUSES,
  CONFIGURATION_STATUSES,
  DISTRIBUTION_DERIVED_GROUPS,
  GOAL_COMPLETION_RULES,
  GOAL_MANUAL_STATUSES,
  GOAL_MEMBERSHIP_ROLES,
  MEASUREMENT_TYPES,
  PROGRESS_STATES,
  STRATEGIC_PLAN_END_YEAR,
  STRATEGIC_PLAN_REPORTING_YEARS,
  STRATEGIC_PLAN_START_YEAR,
  STRATEGY_AUDIT_ACTIONS,
  STRATEGY_AUDIT_ENTITY_TYPES,
  STRATEGY_REPORTING_FREQUENCIES,
  TARGET_SCOPES,
  type AggregationMethod,
  type AverageInputMethod,
  type BoardStatus,
  type ComponentInput,
  type ComponentRecord,
  type ConfigurationGapFields,
  type ConfigurationStatus,
  type DistributionCategoryInput as DistributionBandInput,
  type DistributionCategoryRecord,
  type DistributionDerivedGroup,
  type DistributionInput,
  type DistributionRecord,
  type EffectiveYearRange,
  type GoalCompletionRule as GoalCompletionRuleName,
  type GoalManualStatus,
  type GoalMembershipRole,
  type MeasurementConfigInput,
  type MeasurementConfigRecord,
  type MeasurementType,
  type ObservationInput,
  type ObservationRecord,
  type ProgressState,
  type RawAverageInputs,
  type StrategicGoalInput,
  type StrategicGoalMembershipInput,
  type StrategicGoalMembershipRecord,
  type StrategicGoalRecord,
  type StrategyAuditAction,
  type StrategyAuditEntityType,
  type StrategyAuditEventInput,
  type StrategyAuditEventRecord,
  type StrategyJsonPrimitive,
  type StrategyJsonValue,
  type StrategyRecordMetadata,
  type StrategyReportingFrequency,
  type TargetInput,
  type TargetRecord,
  type TargetScope,
} from "./types";
export * from "./records";
export * from "./validation";
export {
  MEASUREMENT_TYPES as CALCULATION_MEASUREMENT_TYPES,
  calculateAnnualAndPlanProgress,
  calculateGoalCompletion,
  calculateMeasurement,
  calculateProgress,
  calculateStrategyRollups,
  isMeasurementType,
  resolveConfiguredTargetValue,
  rollupGoalCompletions,
  roundFinite,
  type AnnualAndPlanProgressInput,
  type AnnualAndPlanProgressResult,
  type AtomicMeasurementInput,
  type AverageMeasurementInput,
  type AverageMethod,
  type BinaryMeasurementInput,
  type CalculationIssue,
  type CalculationState,
  type ConfiguredTargetValueInput,
  type DistributionCategoryInput,
  type DistributionCategoryResult,
  type DistributionMeasurementInput,
  type DistributionResult,
  type ExcludedGoalKpi,
  type ExcludedGoalReason,
  type GoalCompletionInput,
  type GoalCompletionResult,
  type GoalCompletionRule,
  type GoalCompletionRuleType,
  type GoalKpiExclusionReason,
  type GoalKpiInput,
  type GoalRollupInput,
  type GoalRollupSummary,
  type MeasurementInput,
  type MeasurementResult,
  type MilestoneMeasurementInput,
  type MultiComponentAggregation,
  type MultiComponentInput,
  type MultiComponentMeasurementInput,
  type MultiComponentResult,
  type PercentageMeasurementInput,
  type PriorityGoalRollup,
  type ProgressDirection,
  type ProgressInput,
  type ProgressResult,
  type ProgressStatus,
  type RatioMeasurementInput,
  type ScalarMeasurementInput,
  type StrategyRollups,
  type YearOverYearMeasurementInput,
} from "./calculations";

// Namespaces remain convenient for callers that prefer an explicit domain.
export * as strategyCalculations from "./calculations";
export * as strategyPeriods from "./periods";
